name: flutter_starter_example
description: "See how to run NobodyWho in your Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  get_it: ^9.2.1
  gpt_markdown: ^1.1.8
  http: ^1.6.0
  just_audio: ^0.10.6
  nobodywho: 2.5.0
  path_provider: ^2.1.6
  record: ^7.1.1
  shadcn_ui: ^0.56.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/